language: go
branches:
  only:
  - master

matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.7
  - go: 1.8
  - go: tip
  allow_failures:
  - go: tip

cache:
  directories:
  - "$GOPATH/src"
  - "$GOPATH/pkg"

install:
- make deps
- make restore
- export CI=TRAVIS

script:
- make ci
- if [ "${LATEST}" = "true" ]; then make build; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: nMOxrjSQWr6UX2xKYUdcZuxjj5szAKOijEHhSVwtONrZo0b0Bq3O/Q6qp1q/5csZb3cYX9RN8lviDcw9ASNOOF4HSoAF6yqcPCV0C3a1+MduL+56ooGbHAUSGLLmt90dCsjc4HmeJ3X5DZ1D5glYrxSBRuV0PhVbrqKWARkLmdJRLVU/qd9Z2jg8GEGayLqF9EtIilFdxpG8qqsAvKGo+oj3H5Ba0CtIq96m4NFJBS8Atwxj2Eh3FMgZoqlA41iufeD7nQh2Lr1l86sSCtRjU2TNroaS76Ki5mRVQZs5HII/eTep+/jKEwi9sCgEK9uh88UrVBsxJcndTGCvKa85cjpJNVP2AcCfNYO1tBSfEFJwyBy97/lAjy4W13nvM6eVkVeRjza75HAxoK5QPU73qRp4Ak+YIT1N3Tle8KEwg298RGiMD5B2VESrQEfGq2UfPqnzReWmvohoJECajUgE5gsA4lBafsCT9AYks7CyWeRZhjWhOoItHr29CjHgKj5hCzLtViHeEk40x6h1OCcnC1OY5UVNwMY7CRPYRUujodUJpdUDT/aJyBxEZUBwDINI/nRAdqjZS9AbLr436+0iclLmhAQIVCqgIv3wv/amL1N0uDxrvvyuYWRsPoEBf7Ps54nA4jTn/yyN9K9EUV32UGbZsIJ50uodtv3UZO4w8PM=
  file:
  - bin/templeton
  - bin/templeton_darwin_386
  - bin/templeton_darwin_amd64
  - bin/templeton_linux_386
  - bin/templeton_linux_amd64
  on:
    repo: axelspringer/templeton
    tags: true
    condition: "$LATEST = true"

notifications:
  slack:
    secure: AFsSpuR72iMFuNdOTlWHd6UhFOA3vfaxeXL66+sbILgPC3X1BedKsSQI8w6UIzEE7umks0suKkpDybJD2Doww4c4jNyuIufW+wiVyigaXy3j+fnSouYeGQG6gRIMm33mrHZWoSwUSSxZRvxwW/qNMzAiHURY1cOIwe7IBK7WOiibfStTBO/YjacTw8KGsKPdJ7yXPMlyPH+Wfks1JGk3iKgFY9K69oaETF6P1Uk/DUjos8OqhF83MNrRj4njFl/iVY/1R9iD3mnicGnzrLnljLBplI21kKIn1VsrLqsuuMBxtBkPLDJKAVZueGAS1JOvbOohsVKIbQcCvsr0qD1AJmCI5Sbt1TZQ/uUFGCvjeP2mekQV+ssk00xsxwulSLP8NLr/EnAJjD9mPKfr7JgLk20V/lacymV3JVbM23S66bV+6fWBm70xuaCKgXCfx7usj3aWGE3kXKc5o5+SKhUVeEbk30ZDIjaPOenayD9JSeYUHHpNTN8MrzZljH70ReKpENam14bJ36N4Rv+jspnVNP6ayWc1jt/Cfw2aU0f5CLik6xWbE7PtYd3Fq9fHb6gXT0zjiAWZnUMqe3L43qqzoJzSKOzKDijAHwew3Y6Mz+1EEbuLQezXCRSXSDxz0tMHYb72yT9SK83eVc1Udwks/CweWbvrZ1puVBXVV9vuQp0=
