language: go
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.8
  - go: 1.9
  - go: tip
  allow_failures:
  - go: tip
cache:
  directories:
  - "$GOPATH/src"
  - "$GOPATH/pkg"
install:
- make deps
- make restore
- export CI=TRAVIS
script:
- make ci
- if [ "${LATEST}" = "true" ]; then make build/release; fi
deploy:
  provider: releases
  skip_cleanup: true
  file:
  - bin/penny
  - bin/penny_darwin_386
  - bin/penny_darwin_amd64
  - bin/penny_linux_386
  - bin/penny_linux_amd64
  on:
    repo: andersnormal/penny
    tags: true
    condition: "$LATEST = true"
  api-key:
    secure: tdS+uQyj6lKw+qDSinO6BLSIYOGBXk7QxTh4ChOoQernc01nnVXaNJL2mO1AanfJ2n3B1p+7VcE44T9xuIKpPuMutTySH4suL4npMi3Crbc/FuwnXj9hV9zRNj3EQ0rk3C8F0QjQwmuHLC8knto9xyP3zQiC54qtFqaJSgSBzBfglcv2U+XtCVxOp5YtmJ5IJIxZS0edDSI1Q//Iq7tHar1QiyXpXNTCbsqsTaZQdLhj/ohRJv48YlnVMl95beZ0qZbsISZcqq+wxaosFIkh0eRqNfEzW491am3DPKLI9vwcYAxXa6SUC7xduNs96UzQtRUq1jkmIKuCaJOV3wqYje9YbrgkJZCRNtG6DVx+EbFqrgz9yW9aAhnOp/A7eu6doT8ZtBJ9mlX8OCI4PH99xVXL7fb5Wjns/aOFV5ySl7c4yPj3yaLGfTPrr7xmnLsr6DlQUDMwI1hXxUHdMDZ+If9INpQ5Uh6QRRN4vNRWbZuWtGESIu9GWIrc2Y8k7bFUu9GSqeu5rxn66+o8SboXk30csKKk/8pkLEDAljq5fMcn9AzPDH8KNDe7oXQYvcYwtQlfxkaB9S86o/aetKfQP3LNNAvSPBAXbu/3/G9VTL7OY1yBzmN2MQYWQTY6SoMVwbkg/odaD64Ei//lzuO/lgUwmg75bK0SXSR8zzaZSIY=
notifications:
  slack:
    secure: oEvvNJB8094BrEI13EwTuecoqBhgM+N6OyoIQJwFZTwUNnFCRNb77Jzw4ZBFN3DmX52zw/lN8/JQjLfhWuBXncdToat9n47eWnNcd1iN+x1+q6/hWN6gFKJHeGnNIn/a+9ioJF1OzZjbTCX6eq+85PA4b3dKnYWZUNmtllWkwfiIPGAXJ77u3M296ZwxAf1ip3cJT5M3Qyi37KMuVl688ZTPxBEo42k2MtG3hR/lWi2NsnneP9m4GRTSaJIDWRpmWOeUiBUzJ93GaGmFF1u/QKl9naLzBB045vPBpurIE/VZC9pzXpEOHo6aRr9SpNgqyglpi5Xc7JKAFW35kw5XNcl3lWiDLWgHgMJZoCW6lQYM/S5WDFJjSJo9gApvWOp/AtWZdMSTQTq5A80XIhm6/ehhBwkvgfQ3IuLR/epheK7LW/QhQ3tRjF19kWj8A+BTeppKkUvJrN4wr/CAwWGu7ogq1w5a07fOpUgSEng/4TtSkvoMT1ah7NfV1FxrTMQ6Asa8331G6isc4EYO89zMRu1u9uEEVD20TThNtlJ1M09rdr3Zw7uypL4+KKZqMtsFCQA0Nk9cpfNQgQdeMbSNRttTLpOYaPucPDGXvEe4gtiQMCSqupEwTtIHRJvd1SAvnioztlKMihkiRbxqv1Vj0Egjmd8hTirx97WMJDn1vYQ=
